# -------------------------
# Server
# -------------------------
server.port=8080

# -------------------------
# MongoDB
# -------------------------
spring.data.mongodb.uri=${MONGO_URI}
spring.data.mongodb.database=${MONGO_DB}

# -------------------------
# JWT Configuration
# -------------------------
app.jwt.secret=${JWT_SECRET}

# Token expiration (1 hour = 3600000 ms)
app.jwt.expiration-ms=${JWT_EXPIRATION}

# Remember-me expiration (30 days)
app.jwt.remember-expiration-ms=2592000000

# -------------------------
# Cloudinary
# -------------------------
cloudinary.cloud_name=${CLOUD_NAME}
cloudinary.api_key=${CLOUD_KEY}
cloudinary.api_secret=${CLOUD_SECRET}

# -------------------------
# Logging (Optional but useful on Render)
# -------------------------
logging.level.org.springframework.security=DEBUG
logging.level.com.project.society=DEBUG


RESEND_API_KEY=${RESEND_API_KEY}
