# -------------------------
# Server
# -------------------------
server.port=8080

# -------------------------
# MongoDB
# -------------------------
spring.data.mongodb.uri=${MONGO_URI}
spring.data.mongodb.database=${MONGO_DB}

# -------------------------
# JWT
# -------------------------
app.jwt.secret=${JWT_SECRET}
app.jwt.expiration-ms=${JWT_EXPIRATION}
app.jwt.remember-expiration-ms=2592000000

# -------------------------
# Cloudinary
# -------------------------
cloudinary.cloud_name=${CLOUD_NAME}
cloudinary.api_key=${CLOUD_KEY}
cloudinary.api_secret=${CLOUD_SECRET}

# -------------------------
# ? Resend API Key
# -------------------------
RESEND_API_KEY=${RESEND_API_KEY}

# -------------------------
# Logging
# -------------------------
logging.level.com.project.society=DEBUG
